<!doctype html>

<!--[if lt IE 7]><html <?php language_attributes(); ?> class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if (IE 7)&!(IEMobile)]><html <?php language_attributes(); ?> class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if (IE 8)&!(IEMobile)]><html <?php language_attributes(); ?> class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--> <html <?php language_attributes(); ?> class="no-js"><!--<![endif]-->

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<title><?php wp_title(''); ?></title>

		<link rel="icon" href="<?php echo get_template_directory_uri(); ?>/favicon.png">
		<!--[if IE]>
			<link rel="shortcut icon" href="<?php echo get_template_directory_uri(); ?>/favicon.ico">
		<![endif]-->

        <link rel="stylesheet" type="text/css" href="http://www.woodlandtravelcenter.net/modules/Showtime/templates/css/Show_2.css">
        <link rel="stylesheet" type="text/css" href="http://www.woodlandtravelcenter.net/modules/Showtime/templates/css/Show_3.css">

		<?php wp_head(); ?>

		<?php // drop Google Analytics Here ?>

	</head>

	<body <?php body_class(); ?> cz-shortcut-listen="true">
        <a href="#main" class="skip" tabindex="1">Skip to Content</a>

        <div id="wrapper" class="vcard">
            <?php
            if ( is_front_page()) {
            // Include the featured content template.
            ?>
                <div class="gallery">
                    <!-- gallery -->
                    <div class="visual">
                        <!-- generated by showtime Module start -->
                        <!--<script type="text/javascript">

                            $(document).ready(function(){
                                var lastslide=0;
                                $("#slideshow_2").css("overflow", "hidden");
                                $('ul#slides_2').cycle({
                                    fx: 'fade',
                                    speed:    2000,
                                    timeout:  4000,

                                    pagerEvent: 'mouseover',

                                    random: 1,            fastOnEvent: false,
                                    pauseOnPagerHover: true,
                                    prev: '#prev_2',
                                    next: '#next_2'
                                });

                                $("#slideshow_2").hover(function() {
                                        $("ul#prevnextnav_2").fadeIn();
                                    },
                                    function() {
                                        $("ul#prevnextnav_2").fadeOut();
                                    });

                            });


                        </script>-->

                        <div id="slideshow_2" class="pics" style="overflow: hidden;">

                            <?php
                            if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('homepage_slider_area') ) :
                            endif; ?>

                            <!--<ul id="slides_2" style="position: relative;">
                                <li style="position: absolute; top: 0px; left: 0px; display: block; z-index: 5; opacity: 1; width: 600px; height: 249px;"><a href="http://www.woodlandtravelcenter.net/airstream-motorhomes/" target="_self"><img width="600" height="249" style="position:absolute; left:0px; top:0px;" src="<?php echo get_template_directory_uri(); ?>/uploads/images/wtc_home_slider_200.jpg" alt="" title="wtc_home_slider_200.jpg"></a>                </li>
                                <li style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 600px; height: 249px;"><a href="http://www.woodlandtravelcenter.net/airstream-travel-trailers-OLD/" target="_self"><img width="600" height="249" style="position:absolute; left:0px; top:0px;" src="<?php echo get_template_directory_uri(); ?>/uploads/images/wtc_home_slider_202.jpg" alt="" title="wtc_home_slider_202.jpg"></a>                </li>
                                <li style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 600px; height: 249px;"><a href="http://www.woodlandtravelcenter.net/airstream-travel-trailers-OLD/" target="_self"><img width="600" height="249" style="position:absolute; left:0px; top:0px;" src="<?php echo get_template_directory_uri(); ?>/uploads/images/wtc_home_slider_201.jpg" alt="" title="wtc_home_slider_201.jpg"></a>                </li>
                                <li style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 600px; height: 249px;"><a href="http://www.woodlandtravelcenter.net/service-department-2/" target="_self"><img width="600" height="249" style="position:absolute; left:0px; top:0px;" src="<?php echo get_template_directory_uri(); ?>/uploads/images/wtc_home_slider_203.jpg" alt="" title="wtc_home_slider_203.jpg"></a>                </li>
                            </ul>-->
                        </div>

                        <!-- generated by showtime Module end -->
                    </div>
                    <!-- links -->
                    <ul class="links">
                        <li><a href="http://woodlandtravelcenter.net/airstream-trailers" class="airstream">airstream</a></li>
                        <li><a href="http://woodlandtravelcenter.net/park-model-lifestyle" class="destination">destination</a></li>
                        <li><a href="http://woodlandtravelcenter.net/parts-service/parts/" class="parts">parts &amp; service</a></li>
                        <li><a href="http://woodlandtravelcenter.net/restorations/" class="restorations">restorations</a></li>
                    </ul>
                </div>
            <?php } ?>
            <a href="#nav" class="skip">Skip to Navigation</a>